django/sidewalk/sidewalk/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sidewalk.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
) 

urlpatterns += patterns('authenticate.views',

    url(r'^$', 'index'),
    url(r'^home/$', 'home'),
    url(r'^login/$', 'login_view'),
    url(r'^comments/$', 'comments'),
    url(r'^register/$', 'register'),
    url(r'^dash/$', 'dash'),
    url(r'^dash/current/$', 'dash_next_current_page'),
    url(r'^dash/trending/$', 'dash_next_trending_page'),
    url(r'^dash/complete$', 'completion'),
    url(r'^dash/forfeit$', 'forfeit'),
    url(r'^dash/accept$', 'accept'),
    url(r'^dash/allied/$', 'dash_next_allied_page'),
    url(r'^dash/completion-form$', 'complete_challenges_form'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', 'profile'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/ally$', 'make_ally'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/de-ally$', 'remove_ally'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/timeline/$', 'timeline'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/timeline/quest/$', 'timeline_quest'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/timeline/comment$', 'comment'),
    url(r'^account/$', 'settings'),
    url(r'^account/submit/$', 'settings_submit'),
    url(r'^account/errors/$', 'settings_errors'),
    url(r'^logout/$', 'logout_view'),
    url(r'^help/$', 'help')
    # EXTRA: Add code and corresponding URL for initial usage
)

urlpatterns += patterns('qsearch.views',

    url(r'^search/$', 'index'),
    url(r'^search/keywords/(?P<model>[a-z]+)/$', 'keywords'),
    url(r'^search/submit/$', 'submit'),
    url(r'^search/errors/$', 'search_errors'),
    url(r'^search/(?P<keyword>[a-zA-Z0-9]+)/$', 'query') 

    # TODO: Possible filter encoding in HTTP if browser can't handle memory.
    # Or handle client-side. 

#     # EXTRA: Add code and corresponding URL for initial usage
)

#urlpatterns += patterns('qview.views',
#    url(r'^view/$', 'index'),
#    url(r'^view/current/$', 'current'),
#    url(r'^view/current/keywords/$', 'current_keywords'),
#    url(r'^view/completed/$', 'completed'),
#    url(r'^view/completed/keywords/$', 'completed_keywords'),
#     # EXTRA: Add code and corresponding URL for initial usage
#)

urlpatterns += patterns('qpost.views',
    url(r'^post/$', 'post'),
    url(r'^post/submit$', 'submission'),
    url(r'^post/success/$', 'post_success'),
    url(r'^quest/(?P<quest_id>[1-9][0-9]*)-(?P<quest_poster>[a-zA-Z0-9]+)/$', 'quest'),
    url(r'^quest/(?P<quest_id>[1-9][0-9]*)-(?P<quest_poster>[a-zA-Z0-9]+)/complete$', 'completion'),
    url(r'^quest/(?P<quest_id>[1-9][0-9]*)-(?P<quest_poster>[a-zA-Z0-9]+)/accept$', 'accept'),
    url(r'^quest/(?P<quest_id>[1-9][0-9]*)-(?P<quest_poster>[a-zA-Z0-9]+)/remove$', 'remove'),
    url(r'^quest/(?P<quest_id>[1-9][0-9]*)-(?P<quest_poster>[a-zA-Z0-9]+)/forfeit$', 'forfeit')
    # TODO: Encode form response into HTTP! If necessary.
    # EXTRA: Add code and corresponding URL for initial usage
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/sidewalk/qpost/models.py
from django.db import models
from PIL import Image
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile
import os

class Quest(models.Model):
    name = models.CharField(max_length = 200)
    user_posted_name = models.CharField(max_length = 60)
    description = models.TextField()
    city = models.CharField(max_length = 60)
    icon = models.ImageField(upload_to='icons/quest', blank=True, null=True)
    rating = models.PositiveSmallIntegerField(null=True, blank=True)
    stats = models.CommaSeparatedIntegerField(max_length = 200)
    average_npc = models.DecimalField(max_digits = 6, decimal_places = 3, 
        null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    number_completed_users = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return u"%s posted by %s" % (self.name, self.user_posted_name)
    def save(self):
        super(Quest, self).save()
        if self.icon:
            THUMBNAIL_SIZE = (256, 256)
            filename = str(self.icon.path)
            image = Image.open(filename)
            image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)
            image.save(filename)

        # if miniature and self.photo:
  #           filepath = self.photo.path
  #           size = settings.PHOTO_SIZE # 200
  #           identifier = '_%d.' % size
  #           if filepath.find(identifier) == -1:
  #               image = Image.open(filepath)
  #               image.thumbnail([size, size], Image.ANTIALIAS)
  #               new_filepath = filepath.split('.')
  #               new_filepath = '.'.join(new_filepath[:-1]) + identifier + new_filepath[-1].lower()
  #               try:
  #                   image.save(new_filepath, image.format, quality=90, optimize=1)
  #               except:
  #                   image.save(new_filepath, image.format, quality=90)
  #               # use resized image for photo
  #               photo_name = self.photo.name.split('.')
  #               photo_name = '.'.join(photo_name[:-1]) + identifier + photo_name[-1].lower()
  #               self.photo = photo_name
  #               self.save(miniature=False)
  #               # remove old image
  #               os.remove(filepath) - See more at: http://nanvel.name/weblog/django-resize-image-save/#sthash.hSaTlIxU.dpuf

        # DJANGO_TYPE = self.icon.file.content_type
        # if DJANGO_TYPE == 'image/jpeg':
        #   PIL_TYPE = 'jpeg'
        #   FILE_EXTENSION = 'jpg'
        # elif DJANGO_TYPE == 'image/png':
        #   PIL_TYPE = 'png'
        #   FILE_EXTENSION = 'png'


class Challenge(models.Model):
    quest = models.ForeignKey(Quest)
    description = models.TextField()
    location = models.CharField(max_length = 200)

    def __unicode__(self):
        return self.description

#class QuestVerificationPhoto(models.Model):
#    challenge = models.ForeignKey(Challenge)
#    user_submitted_name = models.CharField(max_length = 60)
#    photo = models.FileField(upload_to='verification_photos')
#    #photo_str = models.CharField(max_length = 60)
#
#    def __unicode__(self):
#       return u"Verification Photo for %s" % self.challenge.description

class ChallengeCertificate(models.Model):
    challenge = models.ForeignKey(Challenge)
    user_submitted_name = models.CharField(max_length = 60)
    ver_photo = models.ImageField(upload_to='verification_photos')
    ver_notes = models.TextField()
    def __unicode__(self):
        return u"Challenge certificate for %s" %self.challenge.description
    
    def save(self):
        super(ChallengeCertificate, self).save()
        if self.ver_photo:
            THUMBNAIL_SIZE = (256, 256)
            filename = str(self.ver_photo.path)
            image = Image.open(filename)
            image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)
            image.save(filename)

django/sidewalk/qsearch/models.py
from django.db import models

# Create your models here.

django/sidewalk/qsearch/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from qpost.models import *
from authenticate.models import QUser
from django.db.models import Q
from qpost.qpostform import *
import json
import random
from django.contrib.auth.models import User

def index(request):
    if (request.user.is_authenticated()):
        message = ""
        quest_example = Quest.objects.all()[:1].get()
        stats = eval(quest_example.stats)
        numstats = len(stats)
        if numstats % 2 == 0:
            numrows = 2
            numcols = numstats / 2
            colwidth = max(1, 12 / numcols) 
        else:
            numrows = 3
            numcols = numstats / 3
            colwidth = max(1, 12 / numcols)
        rows = range(numrows)
        cols = range(numcols)
        context_dict = {
            'numrows': numrows,
            'stat_list': stat_list,
            'numcols': numcols,
            'colwidth': colwidth,
            'rows': rows,
            'cols': cols
        }
      
        city_filter = Quest.objects.filter(city=request.user.quser.location)
        quests = city_filter & Quest.objects.order_by('date_posted').reverse()
        qusers = QUser.objects.all()
        qallies = request.user.quser.allies.all()
        if len(qallies) > 10:
            qallies = random.sample(qallies, 10)
        else:
            qallies = random.sample(qusers, 10)
        if len(quests) >= 10:
            quests = quests[:10] 
        context_dict['message'] = message
        context_dict['quests'] = quests
        context_dict['qallies'] = qallies
        return render(request, 'search.html', context_dict)
    else:
        return HttpResponseRedirect('../home')

def submit(request, page=1):
    if request.method == 'GET':
        if request.GET['model'].strip() == 'Adventurer':
            return user_submit(request, page)
        first = True
        message = ""
        quest_example = Quest.objects.all()[:1].get()
        stats = eval(quest_example.stats)
        numstats = len(stats)
        if numstats % 2 == 0:
            numrows = 2
            numcols = numstats / 2
            colwidth = max(1, 12 / numcols) 
        else:
            numrows = 3
            numcols = numstats / 3
            colwidth = max(1, 12 / numcols)
        rows = range(numrows)
        cols = range(numcols)
        context_dict = {
            'numrows': numrows,
            'stat_list': stat_list,
            'numcols': numcols,
            'colwidth': colwidth,
            'rows': rows,
            'cols': cols,
            'first': first
        }
        keywords_string = request.GET['keywords'].strip()
        filter_string = request.GET['filter'].strip()
        order_string = request.GET['order'].strip()
        if 'page' in request.GET:
            page = int(request.GET['page'])
            context_dict['first'] = False
        results = orderQuestKeywords(request.user.quser, keywords_string, filter_string, order_string, page)
        if (len(results) == 0):
            message = "No results found."
        context_dict['message'] = message
        context_dict['quests'] = results
      
        return render(request, 'search_submit.html', context_dict)
    else:
        return HttpResponseRedirect('../../search')

def user_submit(request, page=1):
    if request.method == 'GET':
        first = True
        message = ""
        quser = request.user.quser 
        stats = eval(quser.stats)
        numstats = len(stats)
        if numstats % 2 == 0:
            numrows = 2
            numcols = numstats / 2
            colwidth = max(1, 12 / numcols)
        else:
            numrows = 3
            numcols = numstats / 3
            colwidth = max(1, 12 / numcols)
        rows = range(numrows)
        cols = range(numcols)
        context_dict = {
            'numrows': numrows,
            'stat_list': stat_list,
            'numcols': numcols,
            'colwidth': colwidth,
            'rows': rows,
            'cols': cols,
            'first': first
        }
        keywords_string = request.GET['keywords'].strip()
        if 'page' in request.GET:
            page = int(request.GET['page'])
            context_dict['first'] = False
        results = orderUserKeywords(request.user.quser, keywords_string, page)
        if len(results) == 0:
            message = "No results found."
        context_dict['message'] = message
        context_dict['qusers'] = results
        return render(request, 'search_user_submit.html', context_dict)
    else:
        return HttpResponseRedirect('../../search')

def orderUserKeywords(quser, keywords_string, page=1):
    keywords = keywords_string.split(" ")
    keyword_counts = {}
    for user in User.objects.all():
        keyword_counts[user] = 0

    for word in keywords:
        results = User.objects.filter(Q(username__icontains = word) | \
                    Q(first_name__icontains = word) | \
                    Q(last_name__icontains = word))
        for user in results: 
            keyword_counts[user] += 1
    for key in keyword_counts.keys():
        if keyword_counts[key] == 0:
            keyword_counts.pop(key)
    ordered_users = sorted(keyword_counts, key=keyword_counts.__getitem__, reverse=True)
    ordered_users = [user.quser for user in ordered_users]
    if page > 1:
        return ordered_users[(page - 1)*20: page*20]
    else:
        return ordered_users[:20]

def orderQuestKeywords(quser, keywords_string, filter_string="All", order_string = "Relevance", page=1):
    keywords = keywords_string.split(" ")
    keyword_counts = {}
    for quest in Quest.objects.all():
        keyword_counts[quest] = 0
 
    city_filter = Quest.objects.filter(city=quser.location)
    if filter_string == "Allies'":
        filter_query = Quest.objects.none()
        for ally in quser.allies.all(): 
            if not filter_query:
                filter_query = ally.current_quests.all()
            else:
                filter_query = filter_query | ally.current_quests.all() 
    elif filter_string == "Completed":
        filter_query = quser.completed_quests.all()
    elif filter_string == "Current":
        filter_query = quser.current_quests.all()
    else:
        filter_query = Quest.objects.all()
    filter_query = filter_query & city_filter

    for word in keywords:
        results = filter_query & (Quest.objects.filter(Q(name__icontains = word) | \
            Q(user_posted_name__icontains = word)))
        for quest in results:
            keyword_counts[quest] += 1
    for key in keyword_counts.keys():
        if keyword_counts[key] == 0:
            keyword_counts.pop(key)
    ordered_quests = sorted(keyword_counts, key = keyword_counts.__getitem__, reverse = True)[:100]
    if (order_string == "Recency"):
        ordered_quests = sorted(ordered_quests, key = lambda quest: quest.date_posted, reverse = True)
    elif (order_string == "Rating"):
        ordered_quests = sorted(ordered_quests, key = lambda quest: quest.rating, reverse = True)
    if page > 1: 
        return ordered_quests[(page - 1)*20: page*20]
    else:
        return ordered_quests[:20]

    return ordered_quests

def keywords(request, model="quest"):
    output = []
    city_filter = Quest.objects.filter(city=request.user.quser.location)
    city_user_filter = User.objects.filter(quser__location=request.user.quser.location)
    if (model == "quest"):
        for quest in city_filter:
            output.append(quest.name)
        for user in city_user_filter: 
            output.append(user.username)
    elif (model == "user"):
        for user in User.objects.all():
            output.append(user.username)
            output.append(user.first_name)
            output.append(user.last_name)
    elif (model == "current"):
        for quest in (request.user.quser.current_quests.all() & city_filter):
            output.append(quest.name)
            output.append(quest.user_posted_name)
    elif (model == "completed"):
        for quest in (request.user.quser.completed_quests.all() & city_filter):
            output.append(quest.name)
            output.append(quest.user_posted_name)
    elif (model == "allied"):
        for ally in request.user.quser.allies.all():
            for quest in (ally.current_quests.all() & city_filter):
                output.append(quest.name)
                output.append(quest.user_posted_name)
    return HttpResponse(json.dumps(output))

def search_errors(request):
    return HttpReponse("<html><body> hihi </body></html>")

def query(request, keyword):
    results = Quest.objects.filter(Q(name__icontains = keyword) | 
        Q(user_posted_name__icontains = keyword))
    challenges = Quest.challenges_set.all()

    if not results:
        return render(request, 'search.html', {
            'quests': results,
            'challenges' : challenges,
            'message' : "No results found."
        })

    else:
        return render(request, 'search.html', {
            'quests': results,
            'challenges' : challenges,
        })

# Create your views here.

django/sidewalk/qsearch/templates/search.html
<!DOCTYPE html>
{% load postingstuff %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <title>Sidewalk - Quest Search</title>

    {% include 'imports.html' %}
    <link href="{% static 'css/search.css' %}" rel="stylesheet">

    <script src="{% static 'js/search.js' %}"></script>

  </head>

<body>

    {% include "navbar.html" %}

<!-- _____________________________________________________________ -->

<div id= "panel">
    <div id="panel-header">
        <div class="page-header">
            <h3>Explore <small>Find your quests, make your allies</small></h3>
        </div>
    </div>

    <div id="content-panel" class="panel panel-default">
    <div class="panel-body">
        <div id="search-big-table">
            <form class="form-group" enctype="multipart/form-data" id="search-form" method="post"> {% csrf_token %}
            <div class="row" id="search-param-row">
                <div class="col-xs-3 search-param" id="keywords-col">
                    <label for="keywords" style="margin: 0"></label>
                    <input id="keywords" name="keywords" maxlength="60" type="text" class="form-control search-form" placeholder="Search by keyword"></input>
                </div>
                <div class="col-xs-1 search-param" id="button-col" style="margin-top:20px">
                    <button type="submit" class="btn btn-default" id="search-button"><span class="glyphicon glyphicon-search"></span></button>
                </div>
                <div class="col-xs-3 search-param" style="margin-top:20px">
                    <select class="form-control" id="search-filter">
                        <option> All </option>
                        <option> Current </option>
                        <option> Completed </option>
                        <option> Allies' </option>
                    </select>
                </div>
                <div class="col-xs-3 search-param" style="margin-top:20px">
                    <select class="form-control" id="search-order">
                        <option> Relevance </option>
                        <option> Recency </option>
                        <option> Rating </option>
                    </select>
                </div>
                <div class="col-xs-2 search-param" style="margin-top:20px">
                    <select class="form-control" id="search-model">
                        <option> Quest </option>
                        <option> Adventurer </option>
                    </select>
                </div>
            </div>  
            </form>      
            <table class="table table-hover table-striped" id="search-small-table">
                <tr>
                    <th></th>
                    <th>Quest Name</th>
                    <th>Poster</th>
                    <th>Skill Rewards</th>
                    <th>Location</th>
                    <th>Rating</th>
                </tr>
                {% for quest in quests %}
                <tr>
                    <td><a href='#'><div class="quest-icon-wrapper">
                        {% thumbnail quest.icon "200x200" padding=True as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="quest-icon"> 
                        {% endthumbnail %}
                    </div></a></td>
                    <td><a href="../quest/{{ quest.id }}-{{ quest.user_posted_name}}"><span class="quest-name">{{ quest.name }}</span></a></td>
                    <td><a href="../profile/{{ quest.user_posted_name }}">{{ quest.user_posted_name }}</a></td>
                    <td><div id="skill-point-container">
                        {% for row in rows %}
                        <div class="row" id="stat-row-{{ row }}">
                            {% for col in cols %}
                            <div class="col-xs-{{ colwidth }} stat-box">
                                <img class="stat-icon" name="{{ row|multiply:numcols|add:col|getval:stat_list }}" src="
                                {% static 'images'%}/{{row|multiply:numcols|add:col|getval:stat_list|lower}}.png" alt="Sexy">
                                <p class="stat-value"> {{ row|multiply:numcols|add:col|getqueststat:quest }} </p>
                            </div> 
                            {% endfor %}
                        </div>
                        {% endfor %}
                    </div></td>
                    <td>
                        <ul> {% for challenge in quest.challenge_set.all %}
                            <li>{{ challenge.location }}</li>
                        {% endfor %}</ul>
                    </td>
                    <td>{{ quest.rating }}</td>
                </tr>
                {% endfor %}
            </table>
            <table class="table table-hover table-striped" style="display: none;" id="user-search-table">
                <tr>
                    <th></th>
                    <th>Username</th>
                    <th>Full Name</th>
                    <th>Skill Points</th>
                    <th>Quest Record</th>
                    <th>City</th>
                </tr>
                {% for quser in qallies %}
                <tr>
                    <td><a href='#'><div class="quest-icon-wrapper">
                        {% thumbnail quser.icon "200x200" padding=True as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="quest-icon"> 
                        {% endthumbnail %}
                    </div></a></td>
                    <td><a href="../profile/{{ quser.user.username }}"><span class="quest-name">{{ quser.user.username }}</span></a></td>
                    <td>{{ quser.user.first_name }} {{ quser.user.last_name }}</td>
                    <td><div id="skill-point-container">
                        {% for row in rows %}
                        <div class="row" id="stat-row-{{ row }}">
                            {% for col in cols %}
                            <div class="col-xs-{{ colwidth }} stat-box">
                                <img class="stat-icon" name="{{ row|multiply:numcols|add:col|getval:stat_list }}" src="
                                {% static 'images'%}/{{row|multiply:numcols|add:col|getval:stat_list|lower}}.png" alt="Sexy">
                                <p class="stat-value"> {{ row|multiply:numcols|add:col|getstatval:quser }} </p>
                            </div> 
                            {% endfor %}
                        </div>
                        {% endfor %}
                    </div></td>
                    <td>
                        <ul> 
                            <li>Completed Quests: {{ quser.completed_quests.count }}</li>
                            <li>Current Quests: {{ quser.current_quests.count }}</li>
                            <li>Posted Quests: {{ quser.posted_quests.count }} </li>
                        </ul>
                    </td>
                    <td>{{ quser.location }}</td>
                </tr>
                {% endfor %}
            </table>
            <!-- <div class="see-more"><a href='#' id="next-results-page">See More</a></div> -->
        </div>
    </div>
    </div>


</div>

    {% include 'comments_panel.html' %}

    
  </body>
</html>


<!--<!DOCTYPE html>
<html>
<body>
    <h1> Quest Search </h1>
    <h1> Username: {{ user.username }} </h1>
    {% if message %}
        <h2> {{ message }} </h2>
    {% else %}
        <ul>
            {% for quest in quests %}
                <li> {{ quest.name }} posted by {{ quest.user_posted_name }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>-->

django/sidewalk/qsearch/templates/search_submit.html
<!DOCTYPE html>
{% load postingstuff %}
{% load static %}
{% load thumbnail %}
{% if first %}
<tbody>
<tr>
    <th></th>
    <th>Quest Name</th>
    <th>Poster</th>
    <th>Skill Rewards</th>
    <th>Location</th>
    <th>Rating</th>
</tr>
{% endif %}
{% for quest in quests %}
<tr>
    <td><a href='#'><div class="quest-icon-wrapper">
        {% thumbnail quest.icon "200x200" padding=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="quest-icon"> 
        {% endthumbnail %}
    </div></a></td>
    <td><a href="../quest/{{ quest.id }}-{{ quest.user_posted_name}}"><span class="quest-name">{{ quest.name }}</span></a></td>
    <td><a href="../profile/{{ quest.user_posted_name }}">{{ quest.user_posted_name }}</a></td>
    <td><div id="skill-point-container">
        {% for row in rows %}
        <div class="row" id="stat-row-{{ row }}">
            {% for col in cols %}
            <div class="col-xs-{{ colwidth }} stat-box">
                <img class="stat-icon" name="{{ row|multiply:numcols|add:col|getval:stat_list }}" src="
                {% static 'images'%}/{{row|multiply:numcols|add:col|getval:stat_list|lower}}.png" alt="Sexy">
                <p class="stat-value"> {{ row|multiply:numcols|add:col|getqueststat:quest }} </p>
            </div> 
            {% endfor %}
        </div>
        {% endfor %}
    </div></td>
    <td>
        <ul> {% for challenge in quest.challenge_set.all %}
            <li>{{ challenge.location }}</li>
        {% endfor %}</ul>
    </td>
    <td>{{ quest.rating }}</td>
</tr>
{% endfor %}
{% if first %}
</tbody>
{% endif %}

django/sidewalk/qsearch/templates/search_user_submit.html
<!DOCTYPE html>
{% load postingstuff %}
{% load static %}
{% load thumbnail %}
{% if first %}
<tbody>
<tr>
    <th></th>
    <th>Username</th>
    <th>Full Name</th>
    <th>Skill Points</th>
    <th>Quest Record</th>
    <th>City</th>
</tr>
{% endif %}
{% for quser in qusers %}
<tr>
    <td><a href='#'><div class="quest-icon-wrapper">
        {% thumbnail quser.icon "200x200" padding=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="quest-icon"> 
        {% endthumbnail %}
    </div></a></td>
    <td><a href="../profile/{{ quser.user.username }}"><span class="quest-name">{{ quser.user.username }}</span></a></td>
    <td>{{ quser.user.first_name }} {{ quser.user.last_name }}</td>
    <td><div id="skill-point-container">
        {% for row in rows %}
        <div class="row" id="stat-row-{{ row }}">
            {% for col in cols %}
            <div class="col-xs-{{ colwidth }} stat-box">
                <img class="stat-icon" name="{{ row|multiply:numcols|add:col|getval:stat_list }}" src="
                {% static 'images'%}/{{row|multiply:numcols|add:col|getval:stat_list|lower}}.png" alt="Sexy">
                <p class="stat-value"> {{ row|multiply:numcols|add:col|getstatval:quser }} </p>
            </div> 
            {% endfor %}
        </div>
        {% endfor %}
    </div></td>
    <td>
        <ul> 
            <li>Completed Quests: {{ quser.completed_quests.count }}</li>
            <li>Current Quests: {{ quser.current_quests.count }}</li>
            <li>Posted Quests: {{ quser.posted_quests.count }} </li>
        </ul>
    </td>
    <td>{{ quser.location }}</td>
</tr>
{% endfor %}
{% if first %}
</tbody>
{% endif %}